components:
  schemas:
    Products:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        photo:
          type: string
          description: Foto del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Stock del producto
      example:
        title: Banana
        photo: https://acdn.mitiendanube.com/stores/001/219/229/products/banana1-39d62a544fc16a2b8016025979095295-640-0.jpg
        price: 25
        stock: 60
  responses:
    res201:
      description: Created
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                description: Successful
              payload:
                $ref: "#/components/schemas/Products"
paths:
  /api/products:
    post:
      summary: Para registrar un producto
      tags:
        - Productos
      requestBody:
        required: true
        description: Data del producto
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Products"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res201"
    get:
      summary: Para ver los productos
      tags:
        - Productos
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Products"
  /api/products/:uid:
    put:
      summary: Para buscar un producto
      tags:
        - Productos
      parameters:
        - name: _id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res201"
    delete:
      summary: Para eliminar un producto
      tags:
        - Productos
      parameters:
        - name: productId
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/responses/res201"
